#!/usr/bin/env node
const os = require("os");
const { spawnSync } = require("child_process");
const path = require("path");
const isWindows = os.platform() === "win32";
const script = isWindows ? "tsclean.ps1" : "tsclean.sh";
const scriptPath = path.join(__dirname, script);
const result = spawnSync(
  isWindows ? "powershell" : "bash",
  [scriptPath, ...process.argv.slice(2)],
  {
    stdio: "inherit",
  }
);
process.exit(result.status);
